CREATE DATABASE ESTATISTICA;

USE ESTATISTICA;

CREATE TABLE REGIAO (
  REG_CODIGO    int(11) PRIMARY KEY AUTO_INCREMENT,
  REG_DESCRICAO varchar(10)    NOT NULL,
  REG_SIGLA     varchar(2)     NOT NULL,
  REG_AREA_KM2  int(11)        NOT NULL,
  REG_VALOR_PIB decimal(15, 2) NOT NULL
);

INSERT INTO REGIAO (REG_DESCRICAO, REG_SIGLA, REG_AREA_KM2, REG_VALOR_PIB)
VALUES
  ('Norte', 'No', 123000, 32250.00),
  ('Sul', 'Su', 432000, 128954.00),
  ('Leste', 'Le', 324987, 87965.00),
  ('Oeste', 'Oe', 34545, 125710.00);

CREATE TABLE CIDADE (
  CID_CODIGO       int(11) PRIMARY KEY AUTO_INCREMENT,
  CID_DESCRICAO    varchar(15) NOT NULL,
  CID_ESTADO       varchar(2)  NOT NULL,
  CID_HABITANTES   int(11)     NOT NULL,
  CID_ECONOMICA    varchar(10) NOT NULL,
  CID_ANO_FUNDACAO int(11)     NOT NULL,
  REG_COD          int(11),
  KEY REG_COD_FK (REG_COD),
  CONSTRAINT REG_COD_FK FOREIGN KEY (REG_COD) REFERENCES REGIAO (REG_CODIGO)
);

INSERT INTO CIDADE (CID_DESCRICAO, CID_ESTADO, CID_HABITANTES, CID_ECONOMICA, CID_ANO_FUNDACAO, REG_COD)
VALUES
  ('Franca', 'SP', 700000, 'Industria', 1900, 1),
  ('Restinga', 'SP', 35000, 'Rural', 1925, 2),
  ('Barbacena', 'MG', 58789, 'Rural', 1845, 3),
  ('Barretos', 'SP', 525000, 'Comércio', 1908, 2);